const koreaMovies = [
  { title: "올드보이", releaseDate: 20031121, director: "박찬욱" },
  { title: "기생충", releaseDate: 20190530, director: "봉준호" },
  { title: "버닝", releaseDate: 20180517, director: "이창동" },
  { title: "하녀", releaseDate: 19601220, director: "김기영" },
  { title: "살인의 추억", releaseDate: 20030424, director: "봉준호" },
  { title: "아가씨", releaseDate: 20160601, director: "박찬욱" },
  { title: "곡성", releaseDate: 20160512, director: "나홍진" },
  { title: "엽기적인 그녀", releaseDate: 20010427, director: "곽재용" },
  { title: "박하사탕", releaseDate: 19991224, director: "이창동" },
  { title: "고지전", releaseDate: 20110720, director: "장훈" },
  { title: "악마를 보았다" },
  { title: "비스티 보이즈"},
  { title: "헤어질 결심", releaseDate: 20220629, director: "박찬욱" },
  { title: "웰컴투 동막골", releaseDate: 20050804, director: "박광현" },
  { title: "Castaway on the Moon",  director: "이해준" },
  { title: "변호인", releaseDate: 20131218, director: "양우석" },
  { title: "자유부인", releaseDate: 19561101, director: "이장호" },
  { title: "철수와 만수", releaseDate: 19881224, director: "김지운" },
  { title: "국제시장" },
  { title: "장화, 홍련" },
  { title: "극한직업" },
  { title: "서편제", director: "임권택" },
  { title: "벌새", releaseDate: 20180919, director: "김보라" },
  { title: "지구를 지켜라" },
  { title: "지금은 맞고 그때는 틀리다", releaseDate: 20150910, director: "홍상수" },
  { title: "8월의 크리스마스", releaseDate: 19981224, director: "허진호" },
  { title: "친절한 금자씨", director: "박찬욱" },
  { title: "실미도" },
  { title: "취화선"},
  { title: "명량", releaseDate: 20140730, director: "김한민" }
];

const classicMovies = [
  { title: "캐스트 어웨이", director: "로버트 저메키스" },
  { title: "라이언 일병 구하기", director: "스티븐 스필버그" },
  { title: "타이타닉", director: "제임스 카메론" },
  { title: "반지의 제왕: 왕의 귀환", director: "피터 잭슨" },
  { title: "쉰들러 리스트", director: "스티븐 스필버그" },
  { title: "포레스트 검프", director: "로버트 저메키스" },
  { title: "인셉션", director: "크리스토퍼 놀란" },
  { title: "그랜드 부다페스트 호텔", director: "웨스 앤더슨" },
  { title: "노인을 위한 나라는 없다", director: "코엔 형제" },
  { title: "다크 나이트", director: "크리스토퍼 놀란" },
  { title: "트레인스포팅", director: "댄니 보일" },
  { title: "어벤져스: 엔드게임", director: "안소니 & 조 루소" },
  { title: "매드 맥스: 분노의 도로", director: "조지 밀러" },
  { title: "라이프 오브 파이", director: "앤 리" },
  { title: "셜록 홈즈", director: "가이 리치" },
  { title: "블레이드 러너 2049", director: "드니 빌뇌브" },
  { title: "굿 윌 헌팅", director: "그렉 맏로" },
  { title: "파이트 클럽", director: "데이비드 핀처" },
  { title: "세 얼간이", director: "라잔 나칼링" },
  { title: "보헤미안 랩소디", director: "브라이언 싱어" },
  { title: "아바타", director: "제임스 카메론" },
  { title: "굿 모닝 베트남", director: "배리 레빈슨" },
  { title: "인생은 아름다워", director: "로베르토 베니니" },
  { title: "소울", director: "피트 닥터" },
  { title: "월-E", director: "앤드류 스탄턴" },
  { title: "허", director: "스파이크 존즈" },
  { title: "우주 전쟁", director: "스티븐 스필버그" },
  { title: "말레피센트", director: "로베르트 스턴버그" },
  { title: "스포트라이트", director: "토마스 맥카시" },
  { title: "미드나잇 인 파리", director: "우디 앨런" },
  { title: "그린 북", director: "피터 패럴리" },
  { title: "슬럼독 밀리어네어", director: "댄니 보일" },
  { title: "천일의 스캔들", director: "아만다 포레스터" },
  { title: "이프 유 세이 소", director: "고맙다" }
];


export default {koreaMovies,classicMovies};